name = "remix-jokes-20221114"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

kv_namespaces = [
  { binding = "RAINDROP_CACHE", id = "b660d85965f847f9981e3d4799bc67cb" }
]

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
ENDPOINT="https://remix-jokes-20221114.digital-shuufei.workers.dev"
